import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderApp from "@/components/HeaderApp";

const geistSans = localFont({
  src: "./fonts/Proxima-Nova-Thin.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Proxima-Nova-Thin.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KOA Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div
        style={{
            backgroundImage: `url('/static/bg.jpg')`,
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            width: '100%',
            imageRendering: 'crisp-edges',
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            zIndex: -1,
        }}
    />
          <HeaderApp />
          {children}
     
      </body>
    </html>
  );
}
